// AN ENUM FOR THE LOYALTYUSER LEVEL
export enum LoyaltyUser {
    GOLD_USER = 'GOLD_USER',
    SILVER_USER = 'SILVER_USER',
    BRONZE_USER = 'BRONZE_USER'
}

// AN ENUM FOR THE ALLOWED PERMISSIONS
export enum Permissions {
    ADMIN = 'ADMIN', 
    READ_ONLY = 'READ_ONLY'
}